const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');

const { createSttService, DEFAULT_SAMPLE_RATE } = require('../server/stt');

test('STT service reports Vosk state without crashing', () => {
  const stt = createSttService({ logger: null, modelPath: '' });
  const status = stt.status();

  assert.equal(status.provider, 'vosk');
  assert.equal(status.sampleRate, DEFAULT_SAMPLE_RATE);
  assert.equal(typeof status.ok, 'boolean');
  assert.match(status.state, /missing|unconfigured|model-missing|configured|ready|error/);
});

test('server wires STT status and websocket stream endpoints', () => {
  const server = fs.readFileSync('server/index.js', 'utf8');
  const sttSource = fs.readFileSync('server/stt.js', 'utf8');
  const security = fs.readFileSync('server/security.js', 'utf8');
  const pkg = fs.readFileSync('package.json', 'utf8');
  const dockerfile = fs.readFileSync('Dockerfile', 'utf8');
  const compose = fs.readFileSync('docker-compose.yml', 'utf8');
  const envExample = fs.readFileSync('.env.example', 'utf8');
  const prodEnvExample = fs.readFileSync('env/prod.env.example', 'utf8');
  const installServer = fs.readFileSync('scripts/install-server.ps1', 'utf8');
  const installVosk = fs.readFileSync('scripts/install-vosk-model.ps1', 'utf8');
  const dockerEnv = fs.readFileSync('scripts/docker-env.ps1', 'utf8');

  assert.match(server, /const \{ createSttService \} = require\('\.\/stt'\)/);
  assert.match(server, /app\.get\('\/api\/stt\/status'/);
  assert.match(server, /app\.post\('\/api\/stt\/token'/);
  assert.match(server, /token: stt\.createSocketToken\(req\.user \|\| \{\}\)/);
  assert.match(server, /stt\.attach\(server\)/);
  assert.match(sttSource, /const SOCKET_TOKEN_TTL_MS = 60 \* 1000/);
  assert.match(sttSource, /const RECOGNIZER_DIAGNOSTIC_INTERVAL_MS = 1000/);
  assert.match(sttSource, /const RECOGNIZER_PROCESS_WARN_MS = 50/);
  assert.match(sttSource, /const RECOGNIZER_INPUT_GAP_WARN_MS = 250/);
  assert.match(sttSource, /function createSocketToken\(user = \{\}\)/);
  assert.match(sttSource, /function consumeSocketToken\(token\)/);
  assert.match(sttSource, /url\.searchParams\.get\('token'\)/);
  assert.match(sttSource, /function sendRecognizerResult\(ws, recognizer, eventType = 'final'\)/);
  assert.match(sttSource, /function createRecognizerStats\(\)/);
  assert.match(sttSource, /function maybeSendRecognizerDiagnostic\(ws, stats, force = false\)/);
  assert.match(sttSource, /area: 'stt-recognizer'/);
  assert.match(sttSource, /recognizerStats\.partials \+= 1/);
  assert.match(sttSource, /recognizerStats\.emptyFinals \+= 1/);
  assert.match(sttSource, /msg\.type === 'flush'/);
  assert.match(sttSource, /new WebSocketServer\(\{ noServer: true \}\)/);
  assert.match(sttSource, /url\.pathname !== '\/api\/stt\/stream'/);
  assert.match(sttSource, /security\.authenticateWebSocketRequest\(req\)/);
  assert.match(security, /async function authenticateWebSocketRequest\(req\)/);
  assert.match(pkg, /"ws":/);
  assert.match(pkg, /"dependencies"[\s\S]*"vosk":/);
  assert.doesNotMatch(pkg, /"optionalDependencies"[\s\S]*"vosk":/);
  assert.match(pkg, /"server:install:faster-whisper":/);
  assert.match(pkg, /"server:install:vosk":/);
  assert.match(dockerfile, /FROM node:18\.17\.1-bookworm-slim/);
  assert.doesNotMatch(dockerfile, /FROM node:20/);
  assert.match(dockerfile, /python3 python3-venv make g\+\+ pkg-config libffi-dev libgomp1/);
  assert.match(dockerfile, /\/opt\/faster-whisper\/bin\/pip install --no-cache-dir faster-whisper/);
  assert.match(dockerfile, /npm ci --omit=dev/);
  assert.doesNotMatch(dockerfile, /--include=optional/);
  assert.match(dockerfile, /node -e "require\('vosk'\); console\.log\('vosk module loaded'\)"/);
  assert.match(dockerfile, /import faster_whisper; print\('faster-whisper module loaded'\)/);
  assert.match(compose, /VOICE_PIPELINE_STT_PROVIDER: \$\{VOICE_PIPELINE_STT_PROVIDER:-faster-whisper\}/);
  assert.match(compose, /FASTER_WHISPER_MODEL: \$\{FASTER_WHISPER_MODEL:-base\.en\}/);
  assert.match(compose, /FASTER_WHISPER_CACHE_DIR: \$\{FASTER_WHISPER_CACHE_DIR:-\/data\/faster-whisper\}/);
  assert.match(compose, /VOSK_MODEL_PATH: \$\{VOSK_MODEL_PATH:-\/stt-models\/vosk-model-small-en-us-0\.15\}/);
  assert.match(compose, /\$\{VOSK_MODEL_DIR:-\.\/stt-models\}:\/stt-models:ro/);
  assert.match(envExample, /VOSK_MODEL_PATH=stt-models\/vosk-model-small-en-us-0\.15/);
  assert.match(envExample, /VOICE_PIPELINE_STT_PROVIDER=faster-whisper/);
  assert.match(envExample, /FASTER_WHISPER_MODEL=base\.en/);
  assert.match(prodEnvExample, /VOSK_MODEL_DIR=\.\/stt-models/);
  assert.match(prodEnvExample, /VOSK_MODEL_PATH=\/stt-models\/vosk-model-small-en-us-0\.15/);
  assert.match(prodEnvExample, /VOICE_PIPELINE_STT_PROVIDER=faster-whisper/);
  assert.match(prodEnvExample, /FASTER_WHISPER_CACHE_DIR=\/data\/faster-whisper/);
  assert.match(installServer, /function Ensure-FasterWhisperPackage/);
  assert.match(installServer, /install-faster-whisper\.ps1/);
  assert.match(installServer, /function Ensure-VoskModelDirectory/);
  assert.match(installServer, /function Test-VoskNodePackage/);
  assert.match(installServer, /npm\.cmd install/);
  assert.doesNotMatch(installServer, /--include=optional/);
  assert.match(installServer, /require\('vosk'\); console\.log\('vosk module loaded'\)/);
  assert.match(installServer, /install-vosk-model\.ps1/);
  assert.match(installServer, /Ensure-VoskModelDirectory/);
  assert.match(installVosk, /vosk-model-small-en-us-0\.15/);
  assert.match(installVosk, /https:\/\/alphacephei\.com\/vosk\/models\/\$ModelName\.zip/);
  assert.match(installVosk, /IsPathRooted\(\$ModelDir\)/);
  assert.match(dockerEnv, /function Ensure-VoskModelForCompose/);
  assert.match(dockerEnv, /install-vosk-model\.ps1/);
  assert.match(dockerEnv, /ModelNameFromContainerPath \$envValues\['VOSK_MODEL_PATH'\]/);
  assert.match(dockerEnv, /if \(\$isUpCommand\) \{\s*Ensure-VoskModelForCompose\s*\}/);
});
